# Generated by Django 3.2.22 on 2023-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carbon_fp_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='carbon_saved_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
